### ISSUE TITLE
Advancements wiped

### ISSUE THREAD

**Issue by Nevkip** [DarkPacks/SkyFactory-4#1476] opened 2020-06-03 00:55 UTC
## Bug Report
My advancements just wiped, and now I can't unlock some advancements because I cannot unlock the first advancements in the line. I don't play on a server.

## Expected Behaviour
I entered the nether, and glitched, some items in my inventory were duped like my overworld cake and advancement book.

## Steps to Reproduce (for bugs)

1.Entered the nether
2.Game glitched, some items duped

![image](https://user-images.githubusercontent.com/66341044/83583603-9b726980-a4f9-11ea-84e3-1994c1722a6e.png)
Advancements are wiped
![image](https://user-images.githubusercontent.com/66341044/83583611-a5946800-a4f9-11ea-9592-7bd64c235c19.png)
But as you can see I've made quite a bit of progress already
## Logs
 

* Client/Server Log:
* Crash Log:

## World Information

* Preset: Sky Factory 4

* Prestige: No
 1.12.2
* Modpack Version world created in: 1.12.2

* Additional Content Installed:

## Client Information
Entered the nether and noticed a glitch happen but only noticed when I exited the nether

* Modpack Version: 1.12.2
* Java Version: 1.12.2
* Launcher Used: Minecraft Launcher
* Memory Allocated:
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sam-kirby** [comment] 2020-06-14 23:58
Restore a backup.

Without information on how the glitch happened there's not much we can do to solve the root cause, so I'm closing this.

**Closed by sam-kirby** 2020-06-14 23:58 UTC
Labels: Status: Cannot Reproduce
