### ISSUE TITLE
glitch: item duplication but thousands of items in seconds

### ISSUE THREAD

**Issue by DubStep101** [DarkPacks/SkyFactory-4#1631] opened 2020-09-05 17:43 UTC
## Bug Description

When placing a cyclic item sorter next to a real filing cabinets filing cabinet and configuring it to put output items into the filing cabinet, items are rapidly added to the item folder with no items actually coming in through the item sorter. Essentially, this glitch allows for infinite item duplication, and can produce thousands of an item in mere seconds.

### Did this behavior use to work in the previous version?

I am not aware as i have only been using the latest version to play a survival world.

## Steps to Reproduce (for bugs)

1. Place down a "real filing cabinets" filing cabinet with a folder with the item of your choice in it.
2. Place down a cyclic item sorter adjacent to the filing cabinet.
3. Configure the item sorter to allow items go through to only the filing cabinet, and you're items are now being infinitely duped.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset: Sky Factory 4
* Prestige Enabled: false
* Modpack Version world created in: 4.1.0 (currently latest version)
* Additional Content Installed: none

## Client Information
* Modpack Version: 4.1.0
* Java Version:
* Launcher Used: twitch
* Memory Allocated:
* Server/LAN/Single Player: single player
* Optifine Installed: false
* Shaders Enabled: false

*NOTE: I answered everything I know where to find. I feel like this bug is really cheaty as its petty item duplication and not even that hard to set up. Please remove it if it is further tested and is actually a problem.

**Comment by Awakened-Redstone** [comment] 2020-09-10 11:27
This dupe is quite of old as I know.

**Comment by sam-kirby** [comment] 2020-09-10 12:43
Duplicate of #548, this is fixed in the latest release (4.2.2)

**Closed by sam-kirby** 2020-09-10 12:43 UTC
Labels: Duplicate, Version: Outdated
