### ISSUE TITLE
macOS Kernel Panic on Closing SkyFactory

### ISSUE THREAD

**Issue by singerstar** [DarkPacks/SkyFactory-4#1487] opened 2020-06-15 01:03 UTC
Bug Report
Starting and quitting sky factory on my MacBook pro results in a hardware error restart numerous times. It's seriously scary.

This kind of restart:
https://support.apple.com/en-us/HT200553

Expected Behaviour
For my computer to stay on??? 

Possible Solution
No idea.

Logs
Client/Server Log:
https://gist.github.com/singerstar/da3207806c025681061f7648553501bf.js

Computer report code:
https://gist.github.com/singerstar/7821ece969377acf4c1ed1e31a6c2785.js

World Information
Preset: tutorial
Prestige: yes
Modpack Version world created in: uh... I don't know how to find that out but I created it about a week ago
Client Information
Modpack Version: 4.1.0
Java Version: 1.8.0_221
Launcher Used: AT launcher
Memory Allocated: 4096 max, initial 512
Server/LAN/Single Player: single player
Optifine Installed: N/A
Shaders Enabled: no

**Comment by sam-kirby** [comment] 2020-06-15 02:09
I can't imagine this is caused directly by a mod, or anything that we have the power to change. I'd be interested to know if you get similar problems if you play other packs?

Your Minecraft log looks entirely normal. Your panic log indicates that a page fault occurred - where something tries to access memory that is not owned by a running process. Mods, and Minecraft in general, run within the Java Virtaul Machine and do not manage their memory directly. If they try to access memory they shouldn't the JVM sees that and crashes the program in a more controlled manner than what you are seeing.

You are running an older version of Java, and it's not impossible that updating to 8u251 would solve your issues.

Your panic log highlights AppleIntelKBLGraphics in the backtrace, as well as IOAcceleratorFamily2. This indicates that the crash occured in your graphics driver. It does not reveal any information as to why or what it was doing at the time.

Graphics drivers are included in macOS and cannot be updated separately. You seem to running the latest version of macOS already, was the crashing occuring before this update?

**Comment by singerstar** [comment] 2020-06-15 02:27
It was not happening before this update, but I opened a few other modpacks
and couldn't get it to replicate the problem. I also have been playing this
version of the modpack in this version of Catalina for more than a week and
today was the first day I had the problem.

I'll try updating Java, but I tried to do that earlier and got confused
because I read that Minecraft runs on a separate thing so I don't
understand how to update it. Could maybe use some direction on that. 😅

Thanks!

**Comment by sam-kirby** [comment] 2020-06-15 02:54
Unfortunately this makes it sound like it's a bit of an intermittent issue, it's possible a mod in this pack is doing something that eventually triggers a crash in the graphics driver when the game is closed, but it's also possible that there's an issue with your installation of macOS (or even macOS in general) and any pack could be affected at some point.

As for updating Java it's really simple - install the updated Java from Oracle's website, make sure ATLauncher is using it. You do this by starting a pack and checking that the log says `Java is... version 1.8.0_251` on the 6th line.

If it's not using the updated Java immediately, you can change it by going to ATLauncher Settings -> Minecraft/Java and selecting a different version by changing Java Path. ATLauncher should try and detect all installed versions.

If you need any further help, I recommend you use the Discord. I'm going to leave this open in case anyone else has this issue.

**Comment by singerstar** [comment] 2020-06-15 02:57
Thanks for the help.

**Comment by sam-kirby** [comment] 2020-06-15 03:09
Apologies, that last paragraph wasn’t overly clear - I meant if you have issues updating Java that I haven’t covered please use the Discord to get help with that.

If however you have more details to add to this issue, such as further crashes or details as to what might cause it, or if the problem goes away with the new Java version please update here.

Sorry for the lack of clarity, it’s quite late here! :)

**Comment by singerstar** [comment] 2020-06-15 03:13
No worries, I figured that's what you meant.

**Comment by sam-kirby** [comment] 2020-07-10 18:35
Closing due to lack of reproduction.

**Closed by sam-kirby** 2020-07-10 18:35 UTC
Labels: Env: Linux/MacOS, Status: Cannot Reproduce
