### ISSUE TITLE
Blocks do not break

### ISSUE THREAD

**Issue by LinkyMinky** [DarkPacks/SkyFactory-4#2169] opened 2022-10-29 20:05 UTC
## Bug Description

Me and my friend are trying to play but we cannot break the starting tree we hit the leaves and they do not break

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment] 2022-10-30 19:22
Duplicate of #2168, which was closed.

**Closed by sam-kirby** 2022-10-30 19:22 UTC
Labels: Env: Server
