### ISSUE TITLE
Can't install mod on Twitch

### ISSUE THREAD

**Issue by anescott** [DarkPacks/SkyFactory-4#1157] opened 2019-07-28 00:49 UTC
## Logs

* Client/Server Log:
* Crash Log:

Hi,
I keep getting object reference not set to an instance of an object whenever I try to install this modpack on twitch, I have updated my java and minecraft. I have reinstalled the twitch app also. Thank you for your help in advance!

**Comment by Lorrees** [comment] 2019-07-28 02:59
I am having this same exact issue, I tried going in and installing a different version with no luck.

**Comment by woodenbell** [comment] 2019-07-28 03:12
Same happenned to me. I took a look at the logs and I'm not really sure but I guess this is the error I'm getting (made the file `txt` because `json` is not supported:

___
[20190728022255-57EC .txt](https://github.com/DarkPacks/SkyFactory-4/files/3438820/20190728022255-57EC.txt)


{
  "timestamp": "2019-07-28T03:07:38.8007837Z",
  "level": "Error",
  "thread": 37456,
  "memory": 131904.0,
  "message": "[InstallTaskManager] InstallTask failure a213b767-5557-4426-8c90-f32f7da51a26 ModpackInstallTask",
  "error": {
    "message": "Exception of type 'Curse.Radium.InstallManagement.InstallTaskFailedException' was thrown.",
    "type": "Curse.Radium.InstallManagement.InstallTaskFailedException",
    "stack": [
      "Curse.Radium.Minecraft.InstallTasks.ModpackInstallTask.Run() in C:\\tc\\7bd7cca0561902d5\\desktop\\Minecraft\\Curse.Radium.Minecraft\\InstallTasks\\ModpackInstallTask.cs:111",
      "Curse.Radium.InstallManagement.InstallTaskManager+<>c__DisplayClass41_0.<ProcessQueue>b__0() in C:\\tc\\7bd7cca0561902d5\\desktop\\Curse.Radium\\InstallManagement\\InstallTaskManager.cs:309",
      "Curse.Common.Extensions.TaskEx+<>c__DisplayClass8_0.<TryRun>b__0() in C:\\tc\\7bd7cca0561902d5\\Components\\Source\\Curse.Common\\Extensions\\TaskEx.cs:77",
      "System.Threading.Tasks.Task.InnerInvoke()",
      "System.Threading.Tasks.Task.Execute()",
      "System.Threading.Tasks.Task.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object,Boolean)",
      "System.Threading.ExecutionContext.Run(ExecutionContext,ContextCallback,Object,Boolean)",
      "System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&)",
      "System.Threading.Tasks.Task.ExecuteEntry(Boolean)",
      "System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()"
    ],
    "innerError": {
      "message": "Object reference not set to an instance of an object.",
      "type": "System.NullReferenceException",
      "stack": [
        "Curse.Radium.Minecraft.Installers.MinecraftModpackInstallerProvider.FetchDependencies(AddonFile,ISet`1) in C:\\tc\\7bd7cca0561902d5\\desktop\\Minecraft\\Curse.Radium.Minecraft\\Installers\\MinecraftModpackInstallerProvider.cs:205",
        "Curse.Radium.Minecraft.Installers.MinecraftModpackInstallerProvider.FetchDependency(Int32,ISet`1) in C:\\tc\\7bd7cca0561902d5\\desktop\\Minecraft\\Curse.Radium.Minecraft\\Installers\\MinecraftModpackInstallerProvider.cs:233",
        "Curse.Radium.Minecraft.Installers.MinecraftModpackInstallerProvider.FetchDependencies(AddonFile,ISet`1) in C:\\tc\\7bd7cca0561902d5\\desktop\\Minecraft\\Curse.Radium.Minecraft\\Installers\\MinecraftModpackInstallerProvider.cs:205",
        "Curse.Radium.Minecraft.Installers.MinecraftModpackInstallerProvider.FetchDependency(Int32,ISet`1) in C:\\tc\\7bd7cca0561902d5\\desktop\\Minecraft\\Curse.Radium.Minecraft\\Installers\\MinecraftModpackInstallerProvider.cs:233",
        "Curse.Radium.Minecraft.Installers.MinecraftModpackInstallerProvider.FetchDependencies(AddonFile,ISet`1) in C:\\tc\\7bd7cca0561902d5\\desktop\\Minecraft\\Curse.Radium.Minecraft\\Installers\\MinecraftModpackInstallerProvider.cs:205",
        "Curse.Radium.Minecraft.Installers.MinecraftModpackInstallerProvider.DoValidateManifest() in C:\\tc\\7bd7cca0561902d5\\desktop\\Minecraft\\Curse.Radium.Minecraft\\Installers\\MinecraftModpackInstallerProvider.cs:187",
        "Curse.Radium.Minecraft.Installers.MinecraftModpackInstallerProvider.Run() in C:\\tc\\7bd7cca0561902d5\\desktop\\Minecraft\\Curse.Radium.Minecraft\\Installers\\MinecraftModpackInstallerProvider.cs:115",
        "Curse.Radium.InstallManagement.BaseInstallTask.RunSynchronously() in C:\\tc\\7bd7cca0561902d5\\desktop\\Curse.Radium\\InstallManagement\\BaseInstallTask.cs:273",
        "Curse.Radium.Minecraft.InstallTasks.ModpackInstallTask.Run() in C:\\tc\\7bd7cca0561902d5\\desktop\\Minecraft\\Curse.Radium.Minecraft\\InstallTasks\\ModpackInstallTask.cs:86"
      ]
    }
  }
}

**Comment by ggtylerr** [comment] 2019-07-28 03:13
From what I can tell, this issue applies to all normal MC modpacks, not just SkyFactory. FTB packs work fine.

I'm guessing this is because it's trying to download a full zip of all the mods included instead of just downloading each one separately (like FTB does)

Not sure though since I'm not Twitch.

The best thing to do at the moment is to just wait for Twitch devs to fix the bug.

**Comment by xJon** [comment] 2019-07-28 05:44
I can confirm I'm experiencing the same problem on multiple different modpacks. Cannot install.

**Comment by sk2048** [comment] 2019-07-28 06:21
This is a twitch issue that we have no control over. It will be resolved by them eventually. In the meantime, you can download the pack through ATLauncher or MultiMC.

**Closed by sk2048** 2019-07-28 06:21 UTC
Labels: triage

**Comment by AdamUlbricht** [comment] 2019-07-28 06:23
I had the same issue trying to install sky factory 4 -4.0.8

Trying a workaround by installing previous version (4.0.5) currently installing mods seperately

**Comment by AdamUlbricht** [comment] 2019-07-28 06:36
Twitch seems to have fixed it
