### ISSUE TITLE
Topography

### ISSUE THREAD

**Issue by Legndary961** [DarkPacks/SkyFactory-4#2144] opened 2022-08-02 19:47 UTC
## Bug Description

 I was afk for a while, logged out of the game and then back on and suddenly I couldn't join in my world

### Did this behavior use to work in the previous version?

 This happened on this version

## Steps to Reproduce (for bugs)

 (It probably wouldn't work on others but...)
1. Just being afk for a while
2. Exiting out of the game completly
3. Joining back to the world after loading up and crashed

## Logs

* Client/Server Log: [](https://pastebin.com/2Hc8hYns)
* Crash Log:  

## World Information
* World Preset: Sky Village
* Prestige Enabled: Yes
* Modpack Version world created in: 4.2.4
* Additional Content Installed: No

## Client Information
* Modpack Version: 4.2.4
* Java Version: 1.12.2
* Launcher Used: CurseForge/Default Mincraft launcher
* Memory Allocated: System memory
* Server/LAN/Single Player: Server
* Optifine Installed:No
* Shaders Enabled:No

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Legndary961** [comment] 2022-08-02 19:48
The Client/Server Log is right here:
https://pastebin.com/2Hc8hYns

**Comment by Legndary961** [comment] 2022-08-02 19:49
The Crash log I couldn't find it

**Comment by sam-kirby** [comment] 2022-08-03 10:25
It's crashing due to world data corruption.

The best solution is to restore a backup; backups are automatically created every 30 minutes by default.

If you need help with restoring a backup, I would suggest asking on Discord: https://discord.gg/darkosto 

As this does not contain any information that would help us identify the cause of the corrupted world data I'm going to close this. It is likely it is just bad luck and not something that can be fixed on our end.

**Closed** 2022-08-03 10:25 UTC
Labels: Env: Server
