### ISSUE TITLE
entries removed

### ISSUE THREAD

**Issue by jazza527763** [DarkPacks/SkyFactory-4#2173] opened 2022-11-07 23:28 UTC
so i opened up my singleplayer world today and there was an error message saying 22 missing entries or something (didnt screenshot it) and when i clicked yes in order to play the world there as missing recipies, mainly i noticed my hopper bonsai farm wasnt autocrafing amber because the amber recipies where gone (checked in JEI too, no recipie avaliable) and so i did the java update which came up on my computer thinking that was it and then on the curseforge modloader i clicked the 3 dots options to repair profile and repair installation hoping that would all resolve as just updating java didnt. then i logged on and now its saying theres 204 missing entries!!!, of which i have a screenshot for

## Bug Description

<!-listed above->

### Did this behavior use to work in the previous version?
no, only started having the issue this morning, saw there was another fourm post about similar 3 hours ago

## Steps to Reproduce (for bugs)

1. open skyfactory?
2.
3.

## Logs
no logs in any crash log

## World Information
* World Preset: defaut
* Prestige Enabled: yes
* Modpack Version world created in: minecraft 1.12.2
* Additional Content Installed: optifine, but that was ages ago

## Client Information
* Modpack Version: 4.2.4
* Java Version: version 8 update 351 (build 1.8.0_351-b10)
* Launcher Used: curseforge
* Memory Allocated: 4096MB
* Server/LAN/Single Player: single player
* Optifine Installed: yes
* Shaders Enabled: no
![skyfac error](https://user-images.githubusercontent.com/117692244/200437166-a558c1ed-b30d-4a5b-be22-ce00de15df23.png)

**Comment by sam-kirby** [comment] 2022-11-07 23:32
Duplicate of #2172

Not a modpack bug, the curseforge launcher is currently broken and won't load a large proportion of packs properly.

**Closed by sam-kirby** 2022-11-07 23:32 UTC

**Comment by samronn** [comment] 2022-11-07 23:34
Does anyone know the status of the curseforge launcher issue?
