### ISSUE TITLE
I found a way to duplicate items, I put video for better explanation.

### ISSUE THREAD

**Issue by FAndresCO** [DarkPacks/SkyFactory-4#1296] opened 2019-10-26 19:30 UTC
Demonstration video [https://youtu.be/3XKWqGNmGzQ ](url)
I started playing this modpack about 3 days ago, I don't know if this bug had already been reported.
I'm sorry for my English, I speak Spanish XD

**Comment by sam-kirby** [comment] 2019-10-26 19:40
Duplicate of #1279

**Closed by sam-kirby** 2019-10-26 19:40 UTC
Labels: triage
