### ISSUE TITLE
SkyFactory 4 Generating continent

### ISSUE THREAD

**Issue by Squaregentleman** [DarkPacks/SkyFactory-4#1205] opened 2019-08-22 09:21 UTC
SkyFactory 4 Generating continent
![A851ZQK}TBMSKKARF0F@(`3](https://user-images.githubusercontent.com/22393739/63502787-d96d4680-c500-11e9-8915-b007c79ff080.png)
![B54(H XS224~CHW4~4T$YMC](https://user-images.githubusercontent.com/22393739/63502795-dc683700-c500-11e9-9f21-af27971813a1.png)
Server default configuration
I tried:
Delete block
Alternative seed
Did not solve
From Google Translate

**Comment by Squaregentleman** [comment] 2019-08-22 10:02
No problem with single player
![21SX(36SNBARN465SG1E~66](https://user-images.githubusercontent.com/22393739/63505878-ec831500-c506-11e9-9dbc-23ee4ff4ce5c.png)

**Comment by Darkosto** [comment] 2019-08-22 22:26
You left the server properties as default and not as the server files suggest for you specific world type? This is not a bug you are required to setup the server properties file as we have suggested in the documentation found in the server zip file and here: http://bit.ly/SF4MPInstructions

**Comment by Squaregentleman** [comment] 2019-08-23 00:55
> 您将服务器属性保留为默认值，而不是服务器文件为您指定的特定世界类型？这不是设置服务器属性文件所需的错误，正如我们在服务器zip文件中找到的文档中所建议的那样：[http](http://bit.ly/SF4MPInstructions)：[//bit.ly/SF4MPInstructions](http://bit.ly/SF4MPInstructions)

![$URQCY3P(OJVNN @PCJNCYD](https://user-images.githubusercontent.com/22393739/63559376-bf287c80-c583-11e9-8dc5-659f47ae67de.png)
I don't know where the configuration is wrong.

**Comment by artdude543** [comment] 2019-08-23 20:12
Closing this as it's user error. As you can tell from the generator setting have additional text which is not valid. Causing said generation of the world.

**Closed by artdude543** 2019-08-23 20:12 UTC
Labels: triage
