### ISSUE TITLE
Possible Scripts issue

### ISSUE THREAD

**Issue by Juju8901** [DarkPacks/SkyFactory-4#1660] opened 2020-09-24 04:21 UTC
## Bug Description
good Evening, I'm an admin on a new SF4 server trying to figure some things out. The crafting recipe for the dirt sapling isnt working, as well as the recipe for the crushing tub; and im also having problems with the dirt acorn not turning into a petrified acorn. Any help would be appreciated.
[23/9/2020 23:09:22 PM] [Client thread/ERROR]: Could not find any matching ingredients to remove: 1xtile.tconstruct.rack@0 tconstruct:rack
this is as much as i could find regarding this kind of error

### Did this behavior use to work in the previous version?
N/A I havent played a previous version of SF4

## Steps to Reproduce (for bugs)
1. If i try to Craft a Crushing tub, it will not work
2.If i try to craft a Dirt sapling, it will not work.
3. If i try to make Dirt Acorns in to Petrified Acorns using a tinkers construct drying rack, it will not work.

## Logs
LOGS ATTACHED
CRAFTTWEAKER.LOG
[message (1).txt](https://github.com/DarkPacks/SkyFactory-4/files/5273409/message.1.txt)

## World Information
* World Preset:Survival
* Prestige Enabled: yes
* Modpack Version world created in:4.2.2
* Additional Content Installed:N/A

## Client Information
* Modpack Version:4.2.2
* Java Version: 8 update 261
* Launcher Used: Twitch/ Curse
* Memory Allocated: 10GBs
* Server/LAN/Single Player:Server
* Optifine Installed: no
* Shaders Enabled:no

## Server Information
* Java Version: 8 261
[message.txt](https://github.com/DarkPacks/SkyFactory-4/files/5273405/message.txt)

* Operating System: LUbuntu
* Hoster/Hosting Solution: Self Hosted
* Sponge (Non-Vanilla Forge) Server: Hybrid

![sf4](https://user-images.githubusercontent.com/71806919/94100360-5349c080-fde2-11ea-809e-f259f26188ad.png)

![SAPLING](https://user-images.githubusercontent.com/71806919/94100519-be939280-fde2-11ea-8f1f-4cabe4fd9541.PNG)

![CRUSHING](https://user-images.githubusercontent.com/71806919/94100535-c4897380-fde2-11ea-896c-ccc35898bfdd.png)

**Comment by sam-kirby** [comment] 2020-09-24 08:47
Mystcraft is not present, causing an error.

**Comment by sam-kirby** [comment] 2020-09-24 10:28
Closing as this is not caused by us

**Closed** 2020-09-24 10:28 UTC
Labels: Env: Server
