### ISSUE TITLE
smelting truffle not giving the right material

### ISSUE THREAD

**Issue by ogrodoug** [DarkPacks/SkyFactory-4#451] opened 2019-04-20 01:12 UTC
## Bug Report
when smelting truffles type;enderpearls in the melter gives molten steel

## Expected Behaviour
It should give resonant ender, 

## World Information

* Preset:  SF4 default

* Prestige: yes
Version 4.0.1
* Modpack Version world created in: 4.0.0

**Comment by itanshi** [comment] 2019-04-21 05:47
smelting quartz bacon give me molten steel. i have a feeling any smelted bacon or truffle gives steel

**Comment by sk2048** [comment] 2019-04-21 20:43
Some truffles/bacon have their melting recipe added by Resource Hogs itself, though this doesn't seem intentional and often returns a different amount to what has been set in scripts.

The remainder are added through scripts and it's these that are giving only steel; because truffle/bacon type is determined in NBT these fail to work as intended as there is no way to add a melting recipe that is sensitive to NBT through modtweaker.

**Comment by Durandle** [comment] 2019-04-26 14:14
it seems odd that gold would not be a default type added the resource hogs but gold bacon also melted into steel
might it be worth disabling melting the bacon and truffles then

**Comment by SSkizz** [comment] 2019-05-25 17:45
Yup, still happening in 4.0.5 with all the resource bacon. Melting it converts it to steel

**Comment by sk2048** [comment] 2019-05-26 08:24
We are aware it is still happening, it is a limitation of ModTweaker, for which a PR has been made to fix. You can keep track of that here: jaredlll08/ModTweaker#720

Until this PR is merged and there is a release of ModTweaker containing it this issue will remain open.

**Comment by sam-kirby** [comment] 2020-06-25 05:11
Closed by dfd8dbb0ee9c226e9d0f0f4becf4bb5da0a5e766

**Closed by sam-kirby** 2020-06-25 05:11 UTC
Labels: Category: Config, Category: Mod, Status: Mod Release Available, Type: Bug
